import type { SiteContent } from "@/lib/schema"

const photo = (seed: string, label: string) => ({
  src: `https://picsum.photos/seed/${seed}/1600/1066`,
  alt: `replace with client photo: ${label}`,
})

export const sampleContent: SiteContent = {
  builderName: "Mill & Grove",
  phone: "555-0100",
  email: "hello@example.com",
  communities: [
    {
      slug: "cedar-ridge",
      name: "Cedar Ridge",
      town: "Millfield",
      status: "available",
      oneLiner: "A wooded edge of town, with room to walk.",
      modelAddress: "12 Ridge Road, Millfield",
      hours: "Thursday–Sunday, 12–5",
      lotLine: "Lots from 50 to 65 feet.",
      hero: photo("cedar-ridge", "Cedar Ridge street"),
      sitePlan: photo("cedar-ridge-plan", "Cedar Ridge site plan"),
    },
    {
      slug: "millbrook",
      name: "Millbrook",
      town: "Ashford",
      status: "selling",
      oneLiner: "A small collection beside the mill race.",
      modelAddress: "8 Brook Lane, Ashford",
      hours: "By appointment",
      lotLine: "Twenty-four lots in phase one.",
      hero: photo("millbrook", "Millbrook model"),
      sitePlan: photo("millbrook-plan", "Millbrook site plan"),
    },
    {
      slug: "north-pasture",
      name: "North Pasture",
      town: "Ashford",
      status: "coming-soon",
      oneLiner: "Open land at the north end of the concession.",
      hours: "Not open yet",
      lotLine: "Release date to follow.",
      hero: photo("north-pasture", "North Pasture fields"),
    },
  ],
  plans: [
    {
      slug: "the-willow",
      communitySlug: "cedar-ridge",
      name: "The Willow",
      beds: "3",
      baths: "2.5",
      garage: "2-Car",
      kind: "Bungalow",
      sqft: 2140,
      price: 890000,
      modelHome: true,
      image: photo("willow-plan", "The Willow"),
      photos: [
        { ...photo("willow-ext", "The Willow"), label: "Exterior" },
        { ...photo("willow-fp", "The Willow floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-ash",
      communitySlug: "millbrook",
      name: "The Ash",
      beds: "4",
      baths: "3",
      garage: "3-Car",
      kind: "Two-storey",
      sqft: 2680,
      price: 980000,
      image: photo("ash-plan", "The Ash"),
      photos: [
        { ...photo("ash-ext", "The Ash"), label: "Exterior" },
        { ...photo("ash-fp", "The Ash floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-cedar",
      communitySlug: "cedar-ridge",
      name: "The Cedar",
      beds: "3",
      baths: "2",
      garage: "2-Car",
      kind: "Bungalow",
      sqft: 1890,
      price: 840000,
      image: photo("cedar-plan", "The Cedar"),
      photos: [
        { ...photo("cedar-ext", "The Cedar"), label: "Exterior" },
        { ...photo("cedar-fp", "The Cedar floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-maple",
      communitySlug: "millbrook",
      name: "The Maple",
      beds: "3",
      baths: "2.5",
      garage: "2.5-Car",
      kind: "Two-storey",
      sqft: 2410,
      price: 925000,
      image: photo("maple-plan", "The Maple"),
      photos: [
        { ...photo("maple-ext", "The Maple"), label: "Exterior" },
        { ...photo("maple-fp", "The Maple floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-birch",
      communitySlug: "north-pasture",
      name: "The Birch",
      beds: "4",
      baths: "3.5",
      garage: "3-Car",
      kind: "Two-storey",
      sqft: 3120,
      price: 1040000,
      image: photo("birch-plan", "The Birch"),
      photos: [
        { ...photo("birch-ext", "The Birch"), label: "Exterior" },
        { ...photo("birch-fp", "The Birch floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-elm",
      communitySlug: "cedar-ridge",
      name: "The Elm",
      beds: "3",
      baths: "2.5",
      garage: "3-Car",
      kind: "Two-storey",
      sqft: 2550,
      price: 960000,
      image: photo("elm-plan", "The Elm"),
      photos: [
        { ...photo("elm-ext", "The Elm"), label: "Exterior" },
        { ...photo("elm-fp", "The Elm floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-oak",
      communitySlug: "millbrook",
      name: "The Oak",
      beds: "4",
      baths: "2.5",
      garage: "3-Car",
      kind: "Two-storey",
      sqft: 2900,
      price: 1010000,
      image: photo("oak-plan", "The Oak"),
      photos: [
        { ...photo("oak-ext", "The Oak"), label: "Exterior" },
        { ...photo("oak-fp", "The Oak floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
    {
      slug: "the-pine",
      communitySlug: "cedar-ridge",
      name: "The Pine",
      beds: "3",
      baths: "2",
      garage: "2-Car",
      kind: "Bungalow",
      sqft: 1720,
      price: 810000,
      image: photo("pine-plan", "The Pine"),
      photos: [
        { ...photo("pine-ext", "The Pine"), label: "Exterior" },
        { ...photo("pine-fp", "The Pine floor plan"), label: "Floor plan", fit: "contain" },
      ],
    },
  ],
  readyHomes: [
    {
      slug: "14-elm-court",
      name: "14 Elm Court",
      communitySlug: "cedar-ridge",
      specLine: "3 bed · 2.5 bath · 2,140 sq ft",
      summary:
        "A finished home on a quiet court. Walk the model this weekend and ask about closing.",
      photo: photo("14-elm", "14 Elm Court"),
      photos: [
        photo("14-elm", "14 Elm Court"),
        photo("14-elm-2", "14 Elm Court kitchen"),
      ],
      price: "$890,000",
      city: "Millfield",
      lat: 43.551,
      lng: -80.249,
    },
    {
      slug: "8-birch-lane",
      name: "8 Birch Lane",
      communitySlug: "millbrook",
      specLine: "4 bed · 3 bath · 2,680 sq ft",
      summary:
        "A larger plan with a south garden. Ready when the current owner’s work is complete.",
      photo: photo("8-birch", "8 Birch Lane"),
      photos: [
        photo("8-birch", "8 Birch Lane"),
        photo("8-birch-2", "8 Birch Lane garden"),
      ],
      price: "$960,000",
      city: "Ashford",
      lat: 43.5488,
      lng: -80.2512,
    },
    {
      slug: "22-maple-row",
      name: "22 Maple Row",
      communitySlug: "millbrook",
      specLine: "3 bed · 2.5 bath · 2,410 sq ft",
      summary: "A two-storey on the mill race, ready this season.",
      photo: photo("22-maple", "22 Maple Row"),
      photos: [
        photo("22-maple", "22 Maple Row"),
        photo("22-maple-2", "22 Maple Row living"),
      ],
      price: "$925,000",
      city: "Ashford",
      lat: 43.5524,
      lng: -80.2478,
    },
    {
      slug: "5-oak-walk",
      name: "5 Oak Walk",
      communitySlug: "cedar-ridge",
      specLine: "3 bed · 2 bath · 1,890 sq ft",
      summary: "A bungalow at the wooded edge of the concession.",
      photo: photo("5-oak", "5 Oak Walk"),
      photos: [
        photo("5-oak", "5 Oak Walk"),
        photo("5-oak-2", "5 Oak Walk rear"),
      ],
      price: "$840,000",
      city: "Millfield",
      lat: 43.5495,
      lng: -80.252,
    },
  ],
}
